// action types 

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const SET_TRANSACTION_METHOD_FILTER = 'SET_TRANSACTION_METHOD_FILTER';
export const TOGGLE_TRANSACTION_FLAG = 'TOGGLE_TRANSACTION_FLAG';
export const SET_TRANSACTION_DOMAIN = 'SET_TRANSACTION_DOMAIN';
export const UPDATE_GLOBAL_DATA = 'UPDATE_GLOBAL_DATA';
export const SET_SOCKET_STATUS = 'SET_SOCKET_STATUS';