// action types 

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const SET_TRANSACTION_METHOD_FILTER = 'SET_TRANSACTION_METHOD_FILTER';
export const TOGGLE_TRANSACTION_FLAG = 'TOGGLE_TRANSACTION_FLAG';
export const SET_TRANSACTION_DOMAIN_FILTER = 'SET_TRANSACTION_DOMAIN_FILTER';